# fly.toml app configuration file generated for grocerieslist on 2024-02-27T16:11:33-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grocerieslist'
primary_region = 'dfw'
console_command = '/rails/bin/rails console'

[build]

[mounts]
source = 'data'
destination = '/data'
initial_size = '1gb'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[checks]
[checks.status]
port = 3000
type = 'http'
interval = '10s'
timeout = '2s'
grace_period = '5s'
method = 'GET'
path = '/up'
protocol = 'http'
tls_skip_verify = false

[checks.status.headers]
X-Forwarded-Proto = 'https'

[[vm]]
size = 'shared-cpu-1x'
# memory = "512mb"

[[statics]]
guest_path = '/rails/public'
url_prefix = '/'
